
server:
port: 80


eigateway:
    mappings:
        -
            name: api_route
            host: api.itheima.com
            destinations: localhost:8092

        -
            name: ithub_route
            host: iothub.itcast.cn
            destinations: localhost:8095

management:
    endpoints:
        web:
            exposure:
                include: "*"