
server:
port: 80


eigateway:
    mappings:
        -
            name: api_route
            host: api.itheima.com
            destinations: localhost:8092

management:
    endpoints:
        web:
            exposure:
                include: "*"
