#mqtt配置
mqtt:
    host: tcp://192.168.62.133:1883
    clientid: mqttjs_e8022a4d0b
    topic: good,test,yes
    username: xiadong/U2arIT
    password: TvxY1Q
    timeout: 10
    keepalive: 20

#mongo配置
spring:
    data:
        mongodb:
            host: 192.168.62.133
            port: 27017
            database: easyiot
server:
    port: 8092
